name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: cargo prep
      run: cargo login  ${{ secrets.CARGO_TOKEN }}
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
    - name: cargo publish
      run: cargo publish
      working-directory: picolang
